 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/objectives", type: :request do
  
  # Objective. As you add validations to Objective, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Objective.create! valid_attributes
      get objectives_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      objective = Objective.create! valid_attributes
      get objective_url(objective)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_objective_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      objective = Objective.create! valid_attributes
      get edit_objective_url(objective)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Objective" do
        expect {
          post objectives_url, params: { objective: valid_attributes }
        }.to change(Objective, :count).by(1)
      end

      it "redirects to the created objective" do
        post objectives_url, params: { objective: valid_attributes }
        expect(response).to redirect_to(objective_url(Objective.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Objective" do
        expect {
          post objectives_url, params: { objective: invalid_attributes }
        }.to change(Objective, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post objectives_url, params: { objective: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested objective" do
        objective = Objective.create! valid_attributes
        patch objective_url(objective), params: { objective: new_attributes }
        objective.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the objective" do
        objective = Objective.create! valid_attributes
        patch objective_url(objective), params: { objective: new_attributes }
        objective.reload
        expect(response).to redirect_to(objective_url(objective))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        objective = Objective.create! valid_attributes
        patch objective_url(objective), params: { objective: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested objective" do
      objective = Objective.create! valid_attributes
      expect {
        delete objective_url(objective)
      }.to change(Objective, :count).by(-1)
    end

    it "redirects to the objectives list" do
      objective = Objective.create! valid_attributes
      delete objective_url(objective)
      expect(response).to redirect_to(objectives_url)
    end
  end
end
