 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/purposes", type: :request do
  
  # Purpose. As you add validations to Purpose, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Purpose.create! valid_attributes
      get purposes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      purpose = Purpose.create! valid_attributes
      get purpose_url(purpose)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_purpose_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      purpose = Purpose.create! valid_attributes
      get edit_purpose_url(purpose)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Purpose" do
        expect {
          post purposes_url, params: { purpose: valid_attributes }
        }.to change(Purpose, :count).by(1)
      end

      it "redirects to the created purpose" do
        post purposes_url, params: { purpose: valid_attributes }
        expect(response).to redirect_to(purpose_url(Purpose.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Purpose" do
        expect {
          post purposes_url, params: { purpose: invalid_attributes }
        }.to change(Purpose, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post purposes_url, params: { purpose: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested purpose" do
        purpose = Purpose.create! valid_attributes
        patch purpose_url(purpose), params: { purpose: new_attributes }
        purpose.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the purpose" do
        purpose = Purpose.create! valid_attributes
        patch purpose_url(purpose), params: { purpose: new_attributes }
        purpose.reload
        expect(response).to redirect_to(purpose_url(purpose))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        purpose = Purpose.create! valid_attributes
        patch purpose_url(purpose), params: { purpose: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested purpose" do
      purpose = Purpose.create! valid_attributes
      expect {
        delete purpose_url(purpose)
      }.to change(Purpose, :count).by(-1)
    end

    it "redirects to the purposes list" do
      purpose = Purpose.create! valid_attributes
      delete purpose_url(purpose)
      expect(response).to redirect_to(purposes_url)
    end
  end
end
